#version: '3'
#
#services:
#    app:
#        image: cakikii/laravel-docker:v2
#        ports:
#            - "8000:80"
#        volumes:
#            - .:/var/www/html
#        environment:
#            - DB_HOST=db
#            - DB_PORT=3306
#            - DB_DATABASE=docker_laravel
#            - DB_USERNAME=docker_laravel
#            - DB_PASSWORD=docker_laravel_password
#        depends_on:
#            - db
#
#    db:
#        image: mysql:8.0
#        environment:
#            - MYSQL_DATABASE=docker_laravel
#            - MYSQL_USER=docker_laravel
#            - MYSQL_PASSWORD=docker_laravel_password
#            - MYSQL_ROOT_PASSWORD=secret
#        ports:
#            - "3306:3306"
#        volumes:
#            - db_data:/var/lib/mysql
version: "3.9"

networks:
    laravel:
        name: laravel

services:
    app:
        container_name: laravel-app-docker
        platform: linux/amd64
        depends_on:
            - mysql
        networks:
            - laravel
        image: cakikii/laravel-docker:v2
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=admin
            - DB_PASSWORD=admin
    composer:
        image: composer:latest
        volumes:
            - .:/app
        working_dir: /app
    mysql:
        container_name: laravel-mysql-docker
        image: mysql:8.0
        restart: always
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
            - MYSQL_ROOT_PASSWORD=admin
        ports:
            - "3306:3306"
        networks:
            - laravel

    web:
        container_name: laravel-web-docker
        image: nginx:stable-alpine
        platform: linux/amd64
        restart: always
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

    phpmyadmin:
        container_name: laravel-phpmyadmin-docker
        image: phpmyadmin:latest
        restart: always
        ports:
            - "81:80"
        depends_on:
            - mysql
        links:
            - "mysql:db"
        networks:
            - laravel
